# Generated by Django 4.2.29 on 2026-04-11 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The @name attribute, e.g. 'publication'", max_length=200, unique=True)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Submission Process',
                'verbose_name_plural': 'Submission Processes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionStepDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.CharField(help_text="The @id attribute, e.g. 'publication'", max_length=200, unique=True)),
                ('heading', models.CharField(blank=True, default='', help_text='i18n key, e.g. submit.progressbar.describe.publication', max_length=500)),
                ('processing_class', models.CharField(blank=True, default='', max_length=500)),
                ('type', models.CharField(blank=True, default='', help_text='step type, e.g. submission-form, upload, license', max_length=100)),
                ('mandatory', models.BooleanField(default=True)),
                ('scope', models.CharField(blank=True, choices=[('submission', 'Submission'), ('workflow', 'Workflow'), ('both', 'Both')], default='', help_text='Scope visibility restriction if any', max_length=20)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Step Definition',
                'verbose_name_plural': 'Step Definitions',
                'ordering': ['step_id'],
            },
        ),
        migrations.AlterField(
            model_name='entitycluster',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entitytypeentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='formconditionalblock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='formfieldoverride',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='formlayout',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metadatafield',
            name='field',
            field=models.CharField(help_text='Dotted field name, e.g. dc.title.alternative', max_length=400, unique=True),
        ),
        migrations.AlterField(
            model_name='metadatafield',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metadataschema',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='metadataschema',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Source XML file, e.g. dc-types.xml', max_length=200),
        ),
        migrations.AlterField(
            model_name='quickpreset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quickpresetfilter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='submissionform',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='submissionformfield',
            name='child_form',
            field=models.ForeignKey(blank=True, help_text='Resolved child form for group fields', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_fields', to='api.submissionform'),
        ),
        migrations.AlterField(
            model_name='submissionformfield',
            name='child_form_name',
            field=models.CharField(blank=True, default='', help_text='For group/inline-group fields: name of the child form', max_length=200),
        ),
        migrations.AlterField(
            model_name='submissionformfield',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='submissionformfield',
            name='input_type',
            field=models.CharField(choices=[('onebox', 'One box'), ('textarea', 'Textarea'), ('twobox', 'Two box'), ('name', 'Name'), ('date', 'Date'), ('series', 'Series'), ('dropdown', 'Dropdown'), ('list', 'List'), ('lookup', 'Lookup'), ('lookup-name', 'Lookup Name'), ('tag', 'Tag'), ('qualdrop_value', 'Qualdrop'), ('group', 'Group'), ('inline-group', 'Inline Group'), ('link', 'Link')], default='onebox', max_length=20),
        ),
        migrations.AlterField(
            model_name='submissionformfield',
            name='language_codes',
            field=models.JSONField(default=list, help_text="List of allowed language codes, e.g. ['en','de']"),
        ),
        migrations.AlterField(
            model_name='submissionformfield',
            name='type_binds',
            field=models.JSONField(default=list, help_text='dc.type values that reveal this field'),
        ),
        migrations.CreateModel(
            name='SubmissionProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('step_id', models.CharField(help_text='References SubmissionStepDefinition.step_id', max_length=200)),
                ('definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_steps', to='api.submissionstepdefinition')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='api.submissionprocess')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('process', 'sort_order')},
            },
        ),
    ]
