# Generated by Django 4.2.29 on 2026-04-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_submissionprocess_submissionstepdefinition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(help_text="DSpace entity type, e.g. 'Funding', 'OrgUnit'", max_length=200)),
                ('collection_id', models.CharField(help_text='Target DSpace collection UUID', max_length=200)),
                ('label', models.CharField(blank=True, default='', help_text='Human-readable description shown in admin UI', max_length=300)),
                ('dc_type_includes', models.JSONField(blank=True, default=list, help_text='dc.type must contain any of these strings (case-insensitive)')),
                ('risfunding_status_in', models.JSONField(blank=True, default=list, help_text='risfunding.status must equal one of these values')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Rules are evaluated in ascending order; first match wins')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Collection Mapping',
                'verbose_name_plural': 'Collection Mappings',
                'ordering': ['sort_order', 'entity_type'],
            },
        ),
    ]
